//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Simai.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MuConvert.Antlr {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SimaiParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ISimaiVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.slideType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSlideType([NotNull] SimaiParser.SlideTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt([NotNull] SimaiParser.IntContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] SimaiParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.modifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModifiers([NotNull] SimaiParser.ModifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.chart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChart([NotNull] SimaiParser.ChartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.notationsAndComma"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotationsAndComma([NotNull] SimaiParser.NotationsAndCommaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.notations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotations([NotNull] SimaiParser.NotationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.noteGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoteGroup([NotNull] SimaiParser.NoteGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.eachNote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEachNote([NotNull] SimaiParser.EachNoteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.bpmTag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBpmTag([NotNull] SimaiParser.BpmTagContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.absulouteStepTag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbsulouteStepTag([NotNull] SimaiParser.AbsulouteStepTagContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.metTag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMetTag([NotNull] SimaiParser.MetTagContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.note"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNote([NotNull] SimaiParser.NoteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.tap"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTap([NotNull] SimaiParser.TapContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.hold"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHold([NotNull] SimaiParser.HoldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.touch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTouch([NotNull] SimaiParser.TouchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.touchHold"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTouchHold([NotNull] SimaiParser.TouchHoldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.duration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDuration([NotNull] SimaiParser.DurationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.beats"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBeats([NotNull] SimaiParser.BeatsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.slideDuration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSlideDuration([NotNull] SimaiParser.SlideDurationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.waitTime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWaitTime([NotNull] SimaiParser.WaitTimeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.asBpm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsBpm([NotNull] SimaiParser.AsBpmContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.slide"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSlide([NotNull] SimaiParser.SlideContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.sharedHeadSlide"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSharedHeadSlide([NotNull] SimaiParser.SharedHeadSlideContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SimaiParser.slideBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSlideBody([NotNull] SimaiParser.SlideBodyContext context);
}
} // namespace MuConvert.Antlr
