//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Simai.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MuConvert.Antlr {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class SimaiParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, WS=14, COMMENT=15, COMMA=16, TAP_TO_STAR=17, 
		STAR_TO_TAP=18, NO_STAR=19, KEY=20, TOUCH_AREA=21, SLIDE_TYPE=22, INT=23, 
		CHART_END=24, MODIFIER=25, FALSE_EACH=26;
	public const int
		RULE_slideType = 0, RULE_int = 1, RULE_number = 2, RULE_modifiers = 3, 
		RULE_chart = 4, RULE_notationsAndComma = 5, RULE_notations = 6, RULE_noteGroup = 7, 
		RULE_eachNote = 8, RULE_bpmTag = 9, RULE_absulouteStepTag = 10, RULE_metTag = 11, 
		RULE_note = 12, RULE_tap = 13, RULE_hold = 14, RULE_touch = 15, RULE_touchHold = 16, 
		RULE_duration = 17, RULE_beats = 18, RULE_slideDuration = 19, RULE_waitTime = 20, 
		RULE_asBpm = 21, RULE_slide = 22, RULE_sharedHeadSlide = 23, RULE_slideBody = 24;
	public static readonly string[] ruleNames = {
		"slideType", "int", "number", "modifiers", "chart", "notationsAndComma", 
		"notations", "noteGroup", "eachNote", "bpmTag", "absulouteStepTag", "metTag", 
		"note", "tap", "hold", "touch", "touchHold", "duration", "beats", "slideDuration", 
		"waitTime", "asBpm", "slide", "sharedHeadSlide", "slideBody"
	};

	private static readonly string[] _LiteralNames = {
		null, "'.'", "'/'", "'('", "')'", "'{'", "'#'", "'}'", "'h'", "'['", "']'", 
		"':'", "'##'", "'*'", null, null, "','", null, "'@'", null, null, null, 
		null, null, "'E'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, "WS", "COMMENT", "COMMA", "TAP_TO_STAR", "STAR_TO_TAP", "NO_STAR", 
		"KEY", "TOUCH_AREA", "SLIDE_TYPE", "INT", "CHART_END", "MODIFIER", "FALSE_EACH"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Simai.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static SimaiParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public SimaiParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public SimaiParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class SlideTypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SLIDE_TYPE() { return GetToken(SimaiParser.SLIDE_TYPE, 0); }
		public SlideTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_slideType; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSlideType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SlideTypeContext slideType() {
		SlideTypeContext _localctx = new SlideTypeContext(Context, State);
		EnterRule(_localctx, 0, RULE_slideType);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 50;
			Match(SLIDE_TYPE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IntContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] KEY() { return GetTokens(SimaiParser.KEY); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode KEY(int i) {
			return GetToken(SimaiParser.KEY, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] INT() { return GetTokens(SimaiParser.INT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT(int i) {
			return GetToken(SimaiParser.INT, i);
		}
		public IntContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_int; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IntContext @int() {
		IntContext _localctx = new IntContext(Context, State);
		EnterRule(_localctx, 2, RULE_int);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 53;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 52;
				_la = TokenStream.LA(1);
				if ( !(_la==KEY || _la==INT) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				}
				State = 55;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==KEY || _la==INT );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IntContext[] @int() {
			return GetRuleContexts<IntContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public IntContext @int(int i) {
			return GetRuleContext<IntContext>(i);
		}
		public NumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumber(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberContext number() {
		NumberContext _localctx = new NumberContext(Context, State);
		EnterRule(_localctx, 4, RULE_number);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 57;
			@int();
			State = 60;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__0) {
				{
				State = 58;
				Match(T__0);
				State = 59;
				@int();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ModifiersContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] MODIFIER() { return GetTokens(SimaiParser.MODIFIER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MODIFIER(int i) {
			return GetToken(SimaiParser.MODIFIER, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] TAP_TO_STAR() { return GetTokens(SimaiParser.TAP_TO_STAR); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TAP_TO_STAR(int i) {
			return GetToken(SimaiParser.TAP_TO_STAR, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STAR_TO_TAP() { return GetTokens(SimaiParser.STAR_TO_TAP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STAR_TO_TAP(int i) {
			return GetToken(SimaiParser.STAR_TO_TAP, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NO_STAR() { return GetTokens(SimaiParser.NO_STAR); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NO_STAR(int i) {
			return GetToken(SimaiParser.NO_STAR, i);
		}
		public ModifiersContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_modifiers; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitModifiers(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ModifiersContext modifiers() {
		ModifiersContext _localctx = new ModifiersContext(Context, State);
		EnterRule(_localctx, 6, RULE_modifiers);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 65;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 34471936L) != 0)) {
				{
				{
				State = 62;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 34471936L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				}
				State = 67;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ChartContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(SimaiParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NotationsAndCommaContext[] notationsAndComma() {
			return GetRuleContexts<NotationsAndCommaContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NotationsAndCommaContext notationsAndComma(int i) {
			return GetRuleContext<NotationsAndCommaContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHART_END() { return GetToken(SimaiParser.CHART_END, 0); }
		public ChartContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_chart; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitChart(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ChartContext chart() {
		ChartContext _localctx = new ChartContext(Context, State);
		EnterRule(_localctx, 8, RULE_chart);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 71;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 3211304L) != 0)) {
				{
				{
				State = 68;
				notationsAndComma();
				}
				}
				State = 73;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 75;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==CHART_END) {
				{
				State = 74;
				Match(CHART_END);
				}
			}

			State = 77;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NotationsAndCommaContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NotationsContext notations() {
			return GetRuleContext<NotationsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA() { return GetToken(SimaiParser.COMMA, 0); }
		public NotationsAndCommaContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_notationsAndComma; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNotationsAndComma(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NotationsAndCommaContext notationsAndComma() {
		NotationsAndCommaContext _localctx = new NotationsAndCommaContext(Context, State);
		EnterRule(_localctx, 10, RULE_notationsAndComma);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 79;
			notations();
			State = 80;
			Match(COMMA);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NotationsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public BpmTagContext[] bpmTag() {
			return GetRuleContexts<BpmTagContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public BpmTagContext bpmTag(int i) {
			return GetRuleContext<BpmTagContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AbsulouteStepTagContext[] absulouteStepTag() {
			return GetRuleContexts<AbsulouteStepTagContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public AbsulouteStepTagContext absulouteStepTag(int i) {
			return GetRuleContext<AbsulouteStepTagContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MetTagContext[] metTag() {
			return GetRuleContexts<MetTagContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public MetTagContext metTag(int i) {
			return GetRuleContext<MetTagContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NoteGroupContext noteGroup() {
			return GetRuleContext<NoteGroupContext>(0);
		}
		public NotationsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_notations; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNotations(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NotationsContext notations() {
		NotationsContext _localctx = new NotationsContext(Context, State);
		EnterRule(_localctx, 12, RULE_notations);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 87;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__2 || _la==T__4) {
				{
				State = 85;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
				case 1:
					{
					State = 82;
					bpmTag();
					}
					break;
				case 2:
					{
					State = 83;
					absulouteStepTag();
					}
					break;
				case 3:
					{
					State = 84;
					metTag();
					}
					break;
				}
				}
				State = 89;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 91;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==KEY || _la==TOUCH_AREA) {
				{
				State = 90;
				noteGroup();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NoteGroupContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NoteContext note() {
			return GetRuleContext<NoteContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public EachNoteContext[] eachNote() {
			return GetRuleContexts<EachNoteContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public EachNoteContext eachNote(int i) {
			return GetRuleContext<EachNoteContext>(i);
		}
		public NoteGroupContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_noteGroup; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNoteGroup(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NoteGroupContext noteGroup() {
		NoteGroupContext _localctx = new NoteGroupContext(Context, State);
		EnterRule(_localctx, 14, RULE_noteGroup);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 93;
			note();
			State = 97;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__1 || _la==FALSE_EACH) {
				{
				{
				State = 94;
				eachNote();
				}
				}
				State = 99;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EachNoteContext : ParserRuleContext {
		public IToken sep;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FALSE_EACH() { return GetToken(SimaiParser.FALSE_EACH, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NoteContext note() {
			return GetRuleContext<NoteContext>(0);
		}
		public EachNoteContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_eachNote; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEachNote(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EachNoteContext eachNote() {
		EachNoteContext _localctx = new EachNoteContext(Context, State);
		EnterRule(_localctx, 16, RULE_eachNote);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100;
			_localctx.sep = TokenStream.LT(1);
			_la = TokenStream.LA(1);
			if ( !(_la==T__1 || _la==FALSE_EACH) ) {
				_localctx.sep = ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 102;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==KEY || _la==TOUCH_AREA) {
				{
				State = 101;
				note();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BpmTagContext : ParserRuleContext {
		public IToken s3;
		public IList<IToken> _lp = new List<IToken>();
		public IToken s4;
		public IList<IToken> _rp = new List<IToken>();
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public BpmTagContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bpmTag; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBpmTag(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BpmTagContext bpmTag() {
		BpmTagContext _localctx = new BpmTagContext(Context, State);
		EnterRule(_localctx, 18, RULE_bpmTag);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 105;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 104;
				_localctx.s3 = Match(T__2);
				_localctx._lp.Add(_localctx.s3);
				}
				}
				State = 107;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==T__2 );
			State = 109;
			number();
			State = 111;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 110;
				_localctx.s4 = Match(T__3);
				_localctx._rp.Add(_localctx.s4);
				}
				}
				State = 113;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==T__3 );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AbsulouteStepTagContext : ParserRuleContext {
		public IToken s5;
		public IList<IToken> _lp = new List<IToken>();
		public IToken s7;
		public IList<IToken> _rp = new List<IToken>();
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public AbsulouteStepTagContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_absulouteStepTag; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAbsulouteStepTag(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AbsulouteStepTagContext absulouteStepTag() {
		AbsulouteStepTagContext _localctx = new AbsulouteStepTagContext(Context, State);
		EnterRule(_localctx, 20, RULE_absulouteStepTag);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 116;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 115;
				_localctx.s5 = Match(T__4);
				_localctx._lp.Add(_localctx.s5);
				}
				}
				State = 118;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==T__4 );
			State = 120;
			Match(T__5);
			State = 121;
			number();
			State = 123;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 122;
				_localctx.s7 = Match(T__6);
				_localctx._rp.Add(_localctx.s7);
				}
				}
				State = 125;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==T__6 );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MetTagContext : ParserRuleContext {
		public IToken s5;
		public IList<IToken> _lp = new List<IToken>();
		public IToken s7;
		public IList<IToken> _rp = new List<IToken>();
		[System.Diagnostics.DebuggerNonUserCode] public IntContext @int() {
			return GetRuleContext<IntContext>(0);
		}
		public MetTagContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_metTag; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMetTag(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MetTagContext metTag() {
		MetTagContext _localctx = new MetTagContext(Context, State);
		EnterRule(_localctx, 22, RULE_metTag);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 128;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 127;
				_localctx.s5 = Match(T__4);
				_localctx._lp.Add(_localctx.s5);
				}
				}
				State = 130;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==T__4 );
			State = 132;
			@int();
			State = 134;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 133;
				_localctx.s7 = Match(T__6);
				_localctx._rp.Add(_localctx.s7);
				}
				}
				State = 136;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==T__6 );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NoteContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SlideContext slide() {
			return GetRuleContext<SlideContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SharedHeadSlideContext[] sharedHeadSlide() {
			return GetRuleContexts<SharedHeadSlideContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public SharedHeadSlideContext sharedHeadSlide(int i) {
			return GetRuleContext<SharedHeadSlideContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TapContext tap() {
			return GetRuleContext<TapContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] KEY() { return GetTokens(SimaiParser.KEY); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode KEY(int i) {
			return GetToken(SimaiParser.KEY, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public HoldContext hold() {
			return GetRuleContext<HoldContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TouchContext touch() {
			return GetRuleContext<TouchContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TouchHoldContext touchHold() {
			return GetRuleContext<TouchHoldContext>(0);
		}
		public NoteContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_note; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNote(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NoteContext note() {
		NoteContext _localctx = new NoteContext(Context, State);
		EnterRule(_localctx, 24, RULE_note);
		int _la;
		try {
			State = 154;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 138;
				slide();
				State = 142;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__12) {
					{
					{
					State = 139;
					sharedHeadSlide();
					}
					}
					State = 144;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 145;
				tap();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 147;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 146;
					Match(KEY);
					}
					}
					State = 149;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( _la==KEY );
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 151;
				hold();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 152;
				touch();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 153;
				touchHold();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TapContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode KEY() { return GetToken(SimaiParser.KEY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ModifiersContext modifiers() {
			return GetRuleContext<ModifiersContext>(0);
		}
		public TapContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tap; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTap(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TapContext tap() {
		TapContext _localctx = new TapContext(Context, State);
		EnterRule(_localctx, 26, RULE_tap);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 156;
			Match(KEY);
			State = 157;
			modifiers();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class HoldContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode KEY() { return GetToken(SimaiParser.KEY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ModifiersContext[] modifiers() {
			return GetRuleContexts<ModifiersContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ModifiersContext modifiers(int i) {
			return GetRuleContext<ModifiersContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DurationContext duration() {
			return GetRuleContext<DurationContext>(0);
		}
		public HoldContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_hold; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHold(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public HoldContext hold() {
		HoldContext _localctx = new HoldContext(Context, State);
		EnterRule(_localctx, 28, RULE_hold);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 159;
			Match(KEY);
			State = 160;
			modifiers();
			State = 161;
			Match(T__7);
			State = 162;
			modifiers();
			State = 166;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__8) {
				{
				State = 163;
				duration();
				State = 164;
				modifiers();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TouchContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TOUCH_AREA() { return GetToken(SimaiParser.TOUCH_AREA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ModifiersContext modifiers() {
			return GetRuleContext<ModifiersContext>(0);
		}
		public TouchContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_touch; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTouch(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TouchContext touch() {
		TouchContext _localctx = new TouchContext(Context, State);
		EnterRule(_localctx, 30, RULE_touch);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 168;
			Match(TOUCH_AREA);
			State = 169;
			modifiers();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TouchHoldContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TOUCH_AREA() { return GetToken(SimaiParser.TOUCH_AREA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ModifiersContext[] modifiers() {
			return GetRuleContexts<ModifiersContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ModifiersContext modifiers(int i) {
			return GetRuleContext<ModifiersContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DurationContext duration() {
			return GetRuleContext<DurationContext>(0);
		}
		public TouchHoldContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_touchHold; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTouchHold(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TouchHoldContext touchHold() {
		TouchHoldContext _localctx = new TouchHoldContext(Context, State);
		EnterRule(_localctx, 32, RULE_touchHold);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 171;
			Match(TOUCH_AREA);
			State = 172;
			modifiers();
			State = 173;
			Match(T__7);
			State = 174;
			modifiers();
			State = 178;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__8) {
				{
				State = 175;
				duration();
				State = 176;
				modifiers();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DurationContext : ParserRuleContext {
		public IToken s9;
		public IList<IToken> _lp = new List<IToken>();
		public IToken s10;
		public IList<IToken> _rp = new List<IToken>();
		[System.Diagnostics.DebuggerNonUserCode] public BeatsContext beats() {
			return GetRuleContext<BeatsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public DurationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_duration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDuration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DurationContext duration() {
		DurationContext _localctx = new DurationContext(Context, State);
		EnterRule(_localctx, 34, RULE_duration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 181;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 180;
				_localctx.s9 = Match(T__8);
				_localctx._lp.Add(_localctx.s9);
				}
				}
				State = 183;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==T__8 );
			State = 188;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case KEY:
			case INT:
				{
				State = 185;
				beats();
				}
				break;
			case T__5:
				{
				State = 186;
				Match(T__5);
				State = 187;
				number();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 191;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 190;
				_localctx.s10 = Match(T__9);
				_localctx._rp.Add(_localctx.s10);
				}
				}
				State = 193;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==T__9 );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BeatsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IntContext[] @int() {
			return GetRuleContexts<IntContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public IntContext @int(int i) {
			return GetRuleContext<IntContext>(i);
		}
		public BeatsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_beats; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBeats(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BeatsContext beats() {
		BeatsContext _localctx = new BeatsContext(Context, State);
		EnterRule(_localctx, 36, RULE_beats);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 195;
			@int();
			State = 196;
			Match(T__10);
			State = 197;
			@int();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SlideDurationContext : ParserRuleContext {
		public IToken s9;
		public IList<IToken> _lp = new List<IToken>();
		public IToken s10;
		public IList<IToken> _rp = new List<IToken>();
		[System.Diagnostics.DebuggerNonUserCode] public BeatsContext beats() {
			return GetRuleContext<BeatsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public WaitTimeContext waitTime() {
			return GetRuleContext<WaitTimeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AsBpmContext asBpm() {
			return GetRuleContext<AsBpmContext>(0);
		}
		public SlideDurationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_slideDuration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSlideDuration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SlideDurationContext slideDuration() {
		SlideDurationContext _localctx = new SlideDurationContext(Context, State);
		EnterRule(_localctx, 38, RULE_slideDuration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 200;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 199;
				_localctx.s9 = Match(T__8);
				_localctx._lp.Add(_localctx.s9);
				}
				}
				State = 202;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==T__8 );
			State = 227;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,28,Context) ) {
			case 1:
				{
				State = 204;
				beats();
				}
				break;
			case 2:
				{
				State = 205;
				Match(T__5);
				State = 206;
				number();
				}
				break;
			case 3:
				{
				State = 207;
				waitTime();
				State = 208;
				Match(T__11);
				State = 209;
				asBpm();
				State = 210;
				Match(T__5);
				State = 213;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,25,Context) ) {
				case 1:
					{
					State = 211;
					beats();
					}
					break;
				case 2:
					{
					State = 212;
					number();
					}
					break;
				}
				}
				break;
			case 4:
				{
				State = 215;
				waitTime();
				State = 216;
				Match(T__11);
				State = 219;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,26,Context) ) {
				case 1:
					{
					State = 217;
					beats();
					}
					break;
				case 2:
					{
					State = 218;
					number();
					}
					break;
				}
				}
				break;
			case 5:
				{
				State = 221;
				asBpm();
				State = 222;
				Match(T__5);
				State = 225;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,27,Context) ) {
				case 1:
					{
					State = 223;
					beats();
					}
					break;
				case 2:
					{
					State = 224;
					number();
					}
					break;
				}
				}
				break;
			}
			State = 230;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 229;
				_localctx.s10 = Match(T__9);
				_localctx._rp.Add(_localctx.s10);
				}
				}
				State = 232;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==T__9 );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WaitTimeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public WaitTimeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_waitTime; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWaitTime(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public WaitTimeContext waitTime() {
		WaitTimeContext _localctx = new WaitTimeContext(Context, State);
		EnterRule(_localctx, 40, RULE_waitTime);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 234;
			number();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AsBpmContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public AsBpmContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_asBpm; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAsBpm(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AsBpmContext asBpm() {
		AsBpmContext _localctx = new AsBpmContext(Context, State);
		EnterRule(_localctx, 42, RULE_asBpm);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 236;
			number();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SlideContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TapContext tap() {
			return GetRuleContext<TapContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SlideBodyContext slideBody() {
			return GetRuleContext<SlideBodyContext>(0);
		}
		public SlideContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_slide; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSlide(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SlideContext slide() {
		SlideContext _localctx = new SlideContext(Context, State);
		EnterRule(_localctx, 44, RULE_slide);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 238;
			tap();
			State = 239;
			slideBody();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SharedHeadSlideContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SlideBodyContext slideBody() {
			return GetRuleContext<SlideBodyContext>(0);
		}
		public SharedHeadSlideContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sharedHeadSlide; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSharedHeadSlide(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SharedHeadSlideContext sharedHeadSlide() {
		SharedHeadSlideContext _localctx = new SharedHeadSlideContext(Context, State);
		EnterRule(_localctx, 46, RULE_sharedHeadSlide);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 241;
			Match(T__12);
			State = 242;
			slideBody();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SlideBodyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SlideTypeContext[] slideType() {
			return GetRuleContexts<SlideTypeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public SlideTypeContext slideType(int i) {
			return GetRuleContext<SlideTypeContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] KEY() { return GetTokens(SimaiParser.KEY); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode KEY(int i) {
			return GetToken(SimaiParser.KEY, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ModifiersContext[] modifiers() {
			return GetRuleContexts<ModifiersContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ModifiersContext modifiers(int i) {
			return GetRuleContext<ModifiersContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SlideDurationContext[] slideDuration() {
			return GetRuleContexts<SlideDurationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public SlideDurationContext slideDuration(int i) {
			return GetRuleContext<SlideDurationContext>(i);
		}
		public SlideBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_slideBody; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISimaiVisitor<TResult> typedVisitor = visitor as ISimaiVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSlideBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SlideBodyContext slideBody() {
		SlideBodyContext _localctx = new SlideBodyContext(Context, State);
		EnterRule(_localctx, 48, RULE_slideBody);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 244;
			slideType();
			State = 245;
			Match(KEY);
			State = 263;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,32,Context) ) {
			case 1:
				{
				State = 251;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==SLIDE_TYPE) {
					{
					{
					State = 246;
					slideType();
					State = 247;
					Match(KEY);
					}
					}
					State = 253;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			case 2:
				{
				State = 260;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,31,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 254;
						slideDuration();
						State = 255;
						slideType();
						State = 256;
						Match(KEY);
						}
						} 
					}
					State = 262;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,31,Context);
				}
				}
				break;
			}
			State = 265;
			modifiers();
			State = 266;
			slideDuration();
			State = 267;
			modifiers();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,26,270,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,1,0,1,0,1,1,4,1,54,8,1,11,1,12,1,55,1,2,
		1,2,1,2,3,2,61,8,2,1,3,5,3,64,8,3,10,3,12,3,67,9,3,1,4,5,4,70,8,4,10,4,
		12,4,73,9,4,1,4,3,4,76,8,4,1,4,1,4,1,5,1,5,1,5,1,6,1,6,1,6,5,6,86,8,6,
		10,6,12,6,89,9,6,1,6,3,6,92,8,6,1,7,1,7,5,7,96,8,7,10,7,12,7,99,9,7,1,
		8,1,8,3,8,103,8,8,1,9,4,9,106,8,9,11,9,12,9,107,1,9,1,9,4,9,112,8,9,11,
		9,12,9,113,1,10,4,10,117,8,10,11,10,12,10,118,1,10,1,10,1,10,4,10,124,
		8,10,11,10,12,10,125,1,11,4,11,129,8,11,11,11,12,11,130,1,11,1,11,4,11,
		135,8,11,11,11,12,11,136,1,12,1,12,5,12,141,8,12,10,12,12,12,144,9,12,
		1,12,1,12,4,12,148,8,12,11,12,12,12,149,1,12,1,12,1,12,3,12,155,8,12,1,
		13,1,13,1,13,1,14,1,14,1,14,1,14,1,14,1,14,1,14,3,14,167,8,14,1,15,1,15,
		1,15,1,16,1,16,1,16,1,16,1,16,1,16,1,16,3,16,179,8,16,1,17,4,17,182,8,
		17,11,17,12,17,183,1,17,1,17,1,17,3,17,189,8,17,1,17,4,17,192,8,17,11,
		17,12,17,193,1,18,1,18,1,18,1,18,1,19,4,19,201,8,19,11,19,12,19,202,1,
		19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,3,19,214,8,19,1,19,1,19,1,19,
		1,19,3,19,220,8,19,1,19,1,19,1,19,1,19,3,19,226,8,19,3,19,228,8,19,1,19,
		4,19,231,8,19,11,19,12,19,232,1,20,1,20,1,21,1,21,1,22,1,22,1,22,1,23,
		1,23,1,23,1,24,1,24,1,24,1,24,1,24,5,24,250,8,24,10,24,12,24,253,9,24,
		1,24,1,24,1,24,1,24,5,24,259,8,24,10,24,12,24,262,9,24,3,24,264,8,24,1,
		24,1,24,1,24,1,24,1,24,0,0,25,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,
		30,32,34,36,38,40,42,44,46,48,0,3,2,0,20,20,23,23,2,0,17,19,25,25,2,0,
		2,2,26,26,285,0,50,1,0,0,0,2,53,1,0,0,0,4,57,1,0,0,0,6,65,1,0,0,0,8,71,
		1,0,0,0,10,79,1,0,0,0,12,87,1,0,0,0,14,93,1,0,0,0,16,100,1,0,0,0,18,105,
		1,0,0,0,20,116,1,0,0,0,22,128,1,0,0,0,24,154,1,0,0,0,26,156,1,0,0,0,28,
		159,1,0,0,0,30,168,1,0,0,0,32,171,1,0,0,0,34,181,1,0,0,0,36,195,1,0,0,
		0,38,200,1,0,0,0,40,234,1,0,0,0,42,236,1,0,0,0,44,238,1,0,0,0,46,241,1,
		0,0,0,48,244,1,0,0,0,50,51,5,22,0,0,51,1,1,0,0,0,52,54,7,0,0,0,53,52,1,
		0,0,0,54,55,1,0,0,0,55,53,1,0,0,0,55,56,1,0,0,0,56,3,1,0,0,0,57,60,3,2,
		1,0,58,59,5,1,0,0,59,61,3,2,1,0,60,58,1,0,0,0,60,61,1,0,0,0,61,5,1,0,0,
		0,62,64,7,1,0,0,63,62,1,0,0,0,64,67,1,0,0,0,65,63,1,0,0,0,65,66,1,0,0,
		0,66,7,1,0,0,0,67,65,1,0,0,0,68,70,3,10,5,0,69,68,1,0,0,0,70,73,1,0,0,
		0,71,69,1,0,0,0,71,72,1,0,0,0,72,75,1,0,0,0,73,71,1,0,0,0,74,76,5,24,0,
		0,75,74,1,0,0,0,75,76,1,0,0,0,76,77,1,0,0,0,77,78,5,0,0,1,78,9,1,0,0,0,
		79,80,3,12,6,0,80,81,5,16,0,0,81,11,1,0,0,0,82,86,3,18,9,0,83,86,3,20,
		10,0,84,86,3,22,11,0,85,82,1,0,0,0,85,83,1,0,0,0,85,84,1,0,0,0,86,89,1,
		0,0,0,87,85,1,0,0,0,87,88,1,0,0,0,88,91,1,0,0,0,89,87,1,0,0,0,90,92,3,
		14,7,0,91,90,1,0,0,0,91,92,1,0,0,0,92,13,1,0,0,0,93,97,3,24,12,0,94,96,
		3,16,8,0,95,94,1,0,0,0,96,99,1,0,0,0,97,95,1,0,0,0,97,98,1,0,0,0,98,15,
		1,0,0,0,99,97,1,0,0,0,100,102,7,2,0,0,101,103,3,24,12,0,102,101,1,0,0,
		0,102,103,1,0,0,0,103,17,1,0,0,0,104,106,5,3,0,0,105,104,1,0,0,0,106,107,
		1,0,0,0,107,105,1,0,0,0,107,108,1,0,0,0,108,109,1,0,0,0,109,111,3,4,2,
		0,110,112,5,4,0,0,111,110,1,0,0,0,112,113,1,0,0,0,113,111,1,0,0,0,113,
		114,1,0,0,0,114,19,1,0,0,0,115,117,5,5,0,0,116,115,1,0,0,0,117,118,1,0,
		0,0,118,116,1,0,0,0,118,119,1,0,0,0,119,120,1,0,0,0,120,121,5,6,0,0,121,
		123,3,4,2,0,122,124,5,7,0,0,123,122,1,0,0,0,124,125,1,0,0,0,125,123,1,
		0,0,0,125,126,1,0,0,0,126,21,1,0,0,0,127,129,5,5,0,0,128,127,1,0,0,0,129,
		130,1,0,0,0,130,128,1,0,0,0,130,131,1,0,0,0,131,132,1,0,0,0,132,134,3,
		2,1,0,133,135,5,7,0,0,134,133,1,0,0,0,135,136,1,0,0,0,136,134,1,0,0,0,
		136,137,1,0,0,0,137,23,1,0,0,0,138,142,3,44,22,0,139,141,3,46,23,0,140,
		139,1,0,0,0,141,144,1,0,0,0,142,140,1,0,0,0,142,143,1,0,0,0,143,155,1,
		0,0,0,144,142,1,0,0,0,145,155,3,26,13,0,146,148,5,20,0,0,147,146,1,0,0,
		0,148,149,1,0,0,0,149,147,1,0,0,0,149,150,1,0,0,0,150,155,1,0,0,0,151,
		155,3,28,14,0,152,155,3,30,15,0,153,155,3,32,16,0,154,138,1,0,0,0,154,
		145,1,0,0,0,154,147,1,0,0,0,154,151,1,0,0,0,154,152,1,0,0,0,154,153,1,
		0,0,0,155,25,1,0,0,0,156,157,5,20,0,0,157,158,3,6,3,0,158,27,1,0,0,0,159,
		160,5,20,0,0,160,161,3,6,3,0,161,162,5,8,0,0,162,166,3,6,3,0,163,164,3,
		34,17,0,164,165,3,6,3,0,165,167,1,0,0,0,166,163,1,0,0,0,166,167,1,0,0,
		0,167,29,1,0,0,0,168,169,5,21,0,0,169,170,3,6,3,0,170,31,1,0,0,0,171,172,
		5,21,0,0,172,173,3,6,3,0,173,174,5,8,0,0,174,178,3,6,3,0,175,176,3,34,
		17,0,176,177,3,6,3,0,177,179,1,0,0,0,178,175,1,0,0,0,178,179,1,0,0,0,179,
		33,1,0,0,0,180,182,5,9,0,0,181,180,1,0,0,0,182,183,1,0,0,0,183,181,1,0,
		0,0,183,184,1,0,0,0,184,188,1,0,0,0,185,189,3,36,18,0,186,187,5,6,0,0,
		187,189,3,4,2,0,188,185,1,0,0,0,188,186,1,0,0,0,189,191,1,0,0,0,190,192,
		5,10,0,0,191,190,1,0,0,0,192,193,1,0,0,0,193,191,1,0,0,0,193,194,1,0,0,
		0,194,35,1,0,0,0,195,196,3,2,1,0,196,197,5,11,0,0,197,198,3,2,1,0,198,
		37,1,0,0,0,199,201,5,9,0,0,200,199,1,0,0,0,201,202,1,0,0,0,202,200,1,0,
		0,0,202,203,1,0,0,0,203,227,1,0,0,0,204,228,3,36,18,0,205,206,5,6,0,0,
		206,228,3,4,2,0,207,208,3,40,20,0,208,209,5,12,0,0,209,210,3,42,21,0,210,
		213,5,6,0,0,211,214,3,36,18,0,212,214,3,4,2,0,213,211,1,0,0,0,213,212,
		1,0,0,0,214,228,1,0,0,0,215,216,3,40,20,0,216,219,5,12,0,0,217,220,3,36,
		18,0,218,220,3,4,2,0,219,217,1,0,0,0,219,218,1,0,0,0,220,228,1,0,0,0,221,
		222,3,42,21,0,222,225,5,6,0,0,223,226,3,36,18,0,224,226,3,4,2,0,225,223,
		1,0,0,0,225,224,1,0,0,0,226,228,1,0,0,0,227,204,1,0,0,0,227,205,1,0,0,
		0,227,207,1,0,0,0,227,215,1,0,0,0,227,221,1,0,0,0,228,230,1,0,0,0,229,
		231,5,10,0,0,230,229,1,0,0,0,231,232,1,0,0,0,232,230,1,0,0,0,232,233,1,
		0,0,0,233,39,1,0,0,0,234,235,3,4,2,0,235,41,1,0,0,0,236,237,3,4,2,0,237,
		43,1,0,0,0,238,239,3,26,13,0,239,240,3,48,24,0,240,45,1,0,0,0,241,242,
		5,13,0,0,242,243,3,48,24,0,243,47,1,0,0,0,244,245,3,0,0,0,245,263,5,20,
		0,0,246,247,3,0,0,0,247,248,5,20,0,0,248,250,1,0,0,0,249,246,1,0,0,0,250,
		253,1,0,0,0,251,249,1,0,0,0,251,252,1,0,0,0,252,264,1,0,0,0,253,251,1,
		0,0,0,254,255,3,38,19,0,255,256,3,0,0,0,256,257,5,20,0,0,257,259,1,0,0,
		0,258,254,1,0,0,0,259,262,1,0,0,0,260,258,1,0,0,0,260,261,1,0,0,0,261,
		264,1,0,0,0,262,260,1,0,0,0,263,251,1,0,0,0,263,260,1,0,0,0,264,265,1,
		0,0,0,265,266,3,6,3,0,266,267,3,38,19,0,267,268,3,6,3,0,268,49,1,0,0,0,
		33,55,60,65,71,75,85,87,91,97,102,107,113,118,125,130,136,142,149,154,
		166,178,183,188,193,202,213,219,225,227,232,251,260,263
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace MuConvert.Antlr
