<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework Condition="'$(IsLinuxBuild)' != 'true'">net10.0-windows10.0.17763.0</TargetFramework>
    <TargetFramework Condition="'$(IsLinuxBuild)' == 'true'">net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../MaiChartManager/MaiChartManager.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="../MuConvert/tests/mai/testset/**/*.ma2" Link="Fixtures/NativeMa2/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <ProjectReference Include="../MuConvert-Alpha/MuConvert.csproj" Aliases="Alpha" />
  </ItemGroup>
</Project>
